## Tarea 2
- Usar anomalies python package
- Implementar multiprocessing para calcular las soluciones

In [34]:
import numpy as np

import multiprocessing as multiprocessing

from anomalies import anomaly
from vector_like import vectorlike_generator

In [35]:
from operator import mul


def compute_anomaly_free_set(data):
    
    l, k = vectorlike_generator(data[0], data[1])
    
    set = anomaly.free(l, k)
    gcd = anomaly.free.gcd
    set_simplified = anomaly.free.simplified
        
    results = {
        'l': l,
        'k': k,
        'set': set,
        'gcd': gcd,
        'set_simplified': set_simplified
    }
    
    return set_simplified#results

In [36]:
a = compute_anomaly_free_set([6, 4])

In [40]:
z = 6
vals = np.arange(3, 12, 1)
LK = np.vstack([np.ones(vals.shape)*z, vals]).T

LK

array([[ 6.,  3.],
       [ 6.,  4.],
       [ 6.,  5.],
       [ 6.,  6.],
       [ 6.,  7.],
       [ 6.,  8.],
       [ 6.,  9.],
       [ 6., 10.],
       [ 6., 11.]])

In [41]:
with multiprocessing.Pool(1) as p:
    info = p.map(compute_anomaly_free_set, LK)

In [42]:
info

[array([-1, -1,  1,  1,  1, -1]),
 array([ -1,   4,   8, -14, -14,  17]),
 array([  1,   2,   5, -10, -11,  13]),
 array([  6, -14, -15,  29,  29, -35]),
 array([ -2,  -4,  -6,  15,  17, -20]),
 array([ -5,  19,  20, -39, -52,  57]),
 array([ -77,  119,  141, -213, -235,  265]),
 array([  3,  -5, -12,  17,  17, -20]),
 array([-1089,  1175,  1583, -1773, -1970,  2074])]